### ISSUE TITLE
Which library to use to build MCT

### ISSUE THREAD

**Issue by nandakishorebhandari** [projecttacoma/cqm-execution#262]
Hi Team,

Could you let me know which library to use cqm or fqm to build a measure calculation tool?

**Comment by birick1** [comment]
Hi @nandakishorebhandari 

The phrase "MCT" has typically been used in the context of FHIR-based measures.  For a quick comparison:

- [cqm-execution](https://github.com/projecttacoma/cqm-execution): Used to calculate QDM-based measures
- [fqm-execution](https://github.com/projecttacoma/fqm-execution): Used to calculate FHIR-based measures

So, in that sense, [fqm-execution](https://github.com/projecttacoma/fqm-execution) is more appropriate for an MCT.

That said, I'll add some information that might be helpful.

There was an MCT Prototype Demo given at the September 2023 connectathon with information being found on the [confluence track page](https://confluence.hl7.org/display/FHIR/2023+-+09+Clinical+Reasoning).  From that demo:

- [Github: MCT](https://github.com/cqframework/mct): Source code from the connectathon demo
- [Github: MCT-IG](https://github.com/cqframework/mct-ig/): The IG used for the demo.  I'll note that the IG is no longer available, but you can build the IG yourself for context.

I'll note that the demo requires setting up a couple servers with an MCT built in to one of those servers, and [fqm-execution](https://github.com/projecttacoma/fqm-execution) was not used in that demo.  The demo also uses some operations not specified in the DEQM IG, so truly treat as a prototype.

That is also to say, that any tool that can execute a FHIR-based measure might be considered an "MCT" and there are a couple open source options available.

**Comment by nandakishorebhandari** [comment]
Thank you, @birick1, for providing the answers. 

Could you please assist me with the following queries:

1. Can you provide me with the list of available certified FHIR-based measures (dQMS) and QDM-based measures? Also, share the link to download the bundles.
2. Could you guide me on how to calculate non-FHIR and QDM-based measures?
3. Do we need to transform patient data from QDM to use QDM-based measures? 

Thank you.

**Comment by birick1** [comment]
Hi @nandakishorebhandari 

Perhaps the best place to start is the [eCQI Resource Center](https://ecqi.healthit.gov/).  At that site, you can download measures, read the specifications, and find tooling and resource information.  I think you can find information on all 3 of your items there.

I also wanted to touch a little on query 2.  QDM-based measures do not accept FHIR Patient data, and FHIR-based measures do not accept QDM Patient data.  Each respective measure type requires the use of data targeting the appropriate model.
